### PR TITLE
Remove tensorflow version in requirements.txt

### PR DESCRIPTION
**Pull request by nedspnt**
Recent version of pip cannot see tensorflow>=2.0.0

### CODE REVIEW

**Comment by mrpeerat** [comment]
Can you give me more specific details about your pip and python versions?

**Comment by nedspnt** [comment]
> 

I'm on pyenv virtual env with Python 3.9.17 and pip 23.1.2, where pip can only see tensorflow 2.13.orc0 and 2.13.0rc1

After running the requirements.txt file, the following error appears.
```
ERROR: Could not find a version that satisfies the requirement tensorflow>=2.0.0 (from versions: 2.13.0rc0, 2.13.0rc1)
```

**Comment by mrpeerat** [comment]
There are three solutions (and I think both of them are fine for you). 
First, downgrade Python to Python 3.6 as shown in the requirement.txt.
Second, upgrade Python to Python 3.10.12 (the same version as google collab)
Third, install TensorFlow 2.13 (it should be fine). 
I just installed seft_cut on google collab and everything looks fine for me. 
image

**Comment by nedspnt** [comment]
Thanks for sharing. My experiment in Colab aligned with yours.

Just a quick note that, in my machine (MacOS Montery M1), I was able to create a workaround by installing tensorflow 2.13 and sefr_cut separately (they can't be in the same requirements.txt to install in using `pip install -r requirements.txt`)

Downgrading to python 3.6 or upgrading to python 3.10 doesn't help, even though the pip version matches exactly with Colab.
```
Could not find a version that satisfies the requirement tensorflow>=2.0.0
```

**Pull request closed without merging**
